---
- name: Enable EPEL
  package:
    name: epel-release
    state: present
  when: ansible_distribution == 'CentOS'
  tags:
    - candlepin-basedeps
    - candlepin

- name: Update ca certs
  package:
    name: ca-certificates
    state: latest
  tags:
    - candlepin-basedeps
    - candlepin
    - system_update

- name: Setting up postgresql repository el7
  yum:
    name: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
    state: present
  when: ansible_distribution_major_version == "el7"

- name: Setting up postgresql repository el8
  yum:
    name: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
    state: present
  when: ansible_distribution_major_version == "el8"

- name: Enable postgresql
  command: yum-config-manager --enable pgdg12

- name: Install base packages
  package:
    name:
      - gcc
      - git
      - haveged
      - jss
      - libxml2-python
      - liquibase
      - make
      - policycoreutils-devel
      - postgresql-jdbc
      - postgresql12
      - postgresql12-server
      - python-psycopg2
      - python-pip
      - qpid-proton-c
      - qpid-proton-c-devel
      - ruby
      - ruby-devel
      - rubygem-bundler
      - rubygem-qpid_proton
      - rubygem-json_pure
      - rubygems
      - tomcat
      - wget
      - zlib
      - zlib-devel
      - createrepo_c
      - rpm-build
      - rpm-sign
      - python-requests
      - expect
      - java-1.8.0-openjdk-devel
      - java-11-openjdk-devel
    state: present
  tags:
    - candlepin-basedeps
    - candlepin

- name: Ensure that all packages are up2date
  package:
    name: "*"
    state: latest
  tags:
    - candlepin-basedeps
    - candlepin
    - system_update

- name: Set Java version (Default Java 11)
  command: bash -c 'sudo update-alternatives --set java /usr/lib/jvm/java-11-openjdk-*/bin/java'

- name: Set Java compiler version (Default Java 11)
  command: bash -c 'sudo update-alternatives --set javac /usr/lib/jvm/java-11-openjdk-11*/bin/javac'
