---
- name: Enable EPEL
  package:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution != 'Fedora'
  tags:
    - candlepin-basedeps
    - candlepin

- name: Determine correct postgresql repo (RHEL/CentOS)
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution != 'Fedora'
  tags:
    - candlepin-basedeps
    - candlepin

- name: Determine correct postgresql repo (Fedora)
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  when:
    - ansible_distribution == 'Fedora'
  tags:
    - candlepin-basedeps
    - candlepin

- name: Install postgresql repository
  yum:
    name: "{{ postgres_repo }}"
    state: present
  tags:
    - candlepin-basedeps
    - candlepin

# - name: Enable postgresql repo
#   yum_repository:
#     name: pgdg12
#     enabled: yes
#   tags:
#     - candlepin-basedeps
#     - candlepin

- name: Install base packages
  package:
    name:
      - gcc
      - git
      - haveged
      - java-1.8.0-openjdk-devel
      - jss
      - libxml2-python
      - liquibase
      - make
      - policycoreutils-devel
      - postgresql-jdbc
      - postgresql12
      - postgresql12-server
      - python-psycopg2
      - python-pip
      - qpid-proton-c
      - qpid-proton-c-devel
      - ruby
      - ruby-devel
      - rubygem-bundler
      - rubygem-qpid_proton
      - rubygem-json_pure
      - rubygems
      - tomcat
      - wget
      - zlib
      - zlib-devel
      - createrepo_c
      - rpm-build
      - rpm-sign
      - python-requests
      - expect
    state: present
  tags:
    - candlepin-basedeps
    - candlepin

- name: Ensure that all packages are up2date
  package:
    name: "*"
    state: latest
  tags:
    - candlepin-basedeps
    - candlepin
    - system_update
