---
- import_tasks: el7/el7_tasks.yml
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version == '7'

- import_tasks: el8/el8_tasks.yml
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version == '8'

- import_tasks: common/cp_debugging.yml
  when:
    - cp_configure_debugging | bool

- import_tasks: common/cp_setup.yml
  become: true
  become_user: "{{candlepin_user}}"

- import_tasks: common/cp_deploy.yml
  become: true
  become_user: "{{candlepin_user}}"
  when:
    - cp_deploy | bool

- import_tasks: common/user_env.yml
  become: true
  become_user: "{{candlepin_user}}"
  when:
    - cp_configure_user_env | bool
