---
- name: "Include base deps tasks"
  ansible.builtin.import_tasks: el8_base_deps.yml

- name: "Include ruby tasks"
  ansible.builtin.import_tasks: el8_ruby.yml
  when:
    - cp_configure_ruby | bool
