---
- name: "Include base deps tasks"
  ansible.builtin.import_tasks: el9_base_deps.yml

- name: "Include ruby tasks"
  ansible.builtin.import_tasks: el9_ruby.yml

- name: "Include postgresql tasks"
  ansible.builtin.import_tasks: el9_postgresql.yml
  when:
    - cp_configure_postgresql | bool

- name: "Include mariadb tasks"
  ansible.builtin.import_tasks: el9_mariadb.yml
  when:
    - cp_configure_mariadb | bool
