---
- name: "Install MariaDB packages"
  become: true
  ansible.builtin.package:
    name:
      - mariadb
      - mariadb-server
      - mariadb-java-client
      - python3-PyMySQL
    state: present
  tags:
    - candlepin
    - mariadb

- name: "Set Candlepin-specific MySQL configuration (collation-server)"
  become: true
  community.general.ini_file:
    path: /etc/my.cnf.d/candlepin.cnf
    mode: '0644'
    section: mysqld
    option: collation-server
    value: utf8_general_ci
    create: true
  tags:
    - candlepin
    - mariadb

- name: "Set Candlepin-specific MySQL configuration (character-set-server)"
  become: true
  community.general.ini_file:
    path: /etc/my.cnf.d/candlepin.cnf
    mode: '0644'
    section: mysqld
    option: character-set-server
    value: utf8
    create: true
  tags:
    - candlepin
    - mariadb

- name: "Set Candlepin-specific MySQL configuration (transaction-isolation)"
  become: true
  community.general.ini_file:
    path: /etc/my.cnf.d/candlepin.cnf
    mode: '0644'
    section: mysqld
    option: transaction-isolation
    value: READ-COMMITTED
    create: true
  tags:
    - candlepin
    - mariadb

- name: "Set Candlepin-specific MySQL configuration (default-time-zone)"
  become: true
  community.general.ini_file:
    path: /etc/my.cnf.d/mariadb-server.cnf
    section: server
    option: default-time-zone
    value: "+00:00"
    create: no
  tags:
    - candlepin
    - mariadb

- name: "Enable and start the MariaDB service"
  become: true
  ansible.builtin.service:
    name: mariadb.service
    enabled: true
    state: started
  tags:
    - candlepin
    - mariadb

- name: "Create the 'candlepin' MariaDB user"
  become: true
  ansible.builtin.command: "mysql --user root --execute=\"CREATE USER IF NOT EXISTS 'candlepin'@'localhost'; GRANT ALL PRIVILEGES on candlepin.* TO 'candlepin'@'localhost' WITH GRANT OPTION;\""
  changed_when: false
  tags:
    - candlepin
    - mariadb

- name: "Create the 'candlepin' MariaDB database"
  community.mysql.mysql_db:
    login_user: candlepin
    name: candlepin
    state: present
  tags:
    - candlepin
    - mariadb
