---
dependency:
  name: galaxy
driver:
  name: containers
platforms:
  - name: instance
    image: "docker.io/geerlingguy/docker-${MOLECULE_DISTRO:-fedora35}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
# github will run the linter; uncomment to have molecule do it
# lint: |
#   set -e
#   yamllint .
#   ansible-lint .
