---
dependency:
  name: galaxy
driver:
  name: podman
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: instance
    image: docker.io/pycontribs/centos:7
    #image: registry.access.redhat.com/ubi7/ubi-init:latest
    command: "/sbin/init"
    tmpfs:
      - /run
      - /run/lock
      - /tmp
      # - /sys/fs/cgroup/systemd
      # - /var/lib/journal
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tty: True
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
