# These tasks must be run as the candlepin user. main.yml imports this file with become_user set to
# {{candlepin_user}}, but if these are included or imported anywhere else, that will likely need to
# be done there as well.
---
# Ensure Candlepin exists before attempting to run deployment
- name: "Deploy Candlepin"
  block:
    - name: "Ensure the Candlepin directory exists"
      stat:
        path: "{{candlepin_home}}"
      register: candlepin_home_dir

    - name: "Check for legacy Candlepin deploy script"
      stat:
        path: "{{candlepin_home}}/server/bin/deploy"
      register: cp_deploy_script_file
      when:
        - candlepin_home_dir.stat.isdir

    - name: "Update Candlepin deploy script path to use legacy path"
      set_fact:
        cp_deploy_script: "{{candlepin_home}}/server/bin/deploy"
      when:
        - candlepin_home_dir.stat.isdir
        - cp_deploy_script_file.stat.exists

    - name: "Execute deploy script"
      command:
        cmd: "{{cp_deploy_script}} {{cp_deploy_args}}"
        chdir: "{{candlepin_home}}"
        warn: false
      when:
        - candlepin_home_dir.stat.isdir
  vars:
    cp_deploy_script: "{{candlepin_home}}/bin/deployment/deploy"
  tags:
    - candlepin
    - candlepin-deploy
