---
- name: "Enable MariaDB DNF modules"
  become: true
  ansible.builtin.command:
    cmd: dnf module -y enable mariadb
    warn: false
  changed_when: false
  when:
    - ansible_facts['distribution'] in ["CentOS", "RedHat"]
    - ansible_facts['distribution_major_version'] == "8"
  tags:
    - candlepin
    - mariadb

- name: "Install MariaDB packages"
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ mariadb_packages }}"
  tags:
    - candlepin
    - mariadb

- name: "Set Candlepin-specific MySQL configuration (collation-server)"
  become: true
  community.general.ini_file:
    path: /etc/my.cnf.d/candlepin.cnf
    mode: '0644'
    section: mysqld
    option: collation-server
    value: utf8_general_ci
    create: true
  tags:
    - candlepin
    - mariadb

- name: "Set Candlepin-specific MySQL configuration (character-set-server)"
  become: true
  community.general.ini_file:
    path: /etc/my.cnf.d/candlepin.cnf
    mode: '0644'
    section: mysqld
    option: character-set-server
    value: utf8
    create: true
  tags:
    - candlepin
    - mariadb

- name: "Set Candlepin-specific MySQL configuration (transaction-isolation)"
  become: true
  community.general.ini_file:
    path: /etc/my.cnf.d/candlepin.cnf
    mode: '0644'
    section: mysqld
    option: transaction-isolation
    value: READ-COMMITTED
    create: true
  tags:
    - candlepin
    - mariadb

- name: "Set Candlepin-specific MySQL configuration (default-time-zone)"
  become: true
  community.general.ini_file:
    path: "{{ mariadb_config_file }}"
    section: server
    option: default-time-zone
    value: "+00:00"
    create: no
  tags:
    - candlepin
    - mariadb

- name: "Enable and start the MariaDB service"
  become: true
  ansible.builtin.service:
    name: mariadb.service
    enabled: true
    state: started
  tags:
    - candlepin
    - mariadb

- name: "Create the 'candlepin' MariaDB user"
  become: true
  community.mysql.mysql_user:
    name: candlepin
    priv: "candlepin.*:ALL,GRANT"
    state: present
  when:
    - ansible_distribution in ["CentOS", "RedHat"] and ansible_distribution_major_version <= "8"
      or ansible_distribution == "Fedora" and ansible_distribution_major_version <= "34"
  tags:
    - candlepin
    - mariadb

- name: "Create the 'candlepin' MariaDB user"
  become: true
  ansible.builtin.command: "mysql --user root --execute=\"CREATE USER IF NOT EXISTS 'candlepin'@'localhost'; GRANT ALL PRIVILEGES on candlepin.* TO 'candlepin'@'localhost' WITH GRANT OPTION;\""
  changed_when: false
  when:
    - ansible_distribution in ["CentOS", "RedHat"] and ansible_distribution_major_version == "9"
      or ansible_distribution == "Fedora" and ansible_distribution_major_version >= "35"
  tags:
    - candlepin
    - mariadb

- name: "Create the 'candlepin' MariaDB database"
  community.mysql.mysql_db:
    login_user: candlepin
    name: candlepin
    state: present
  tags:
    - candlepin
    - mariadb
