---
- name: Ensure required openssl is installed
  ansible.builtin.command: "{{ rvm_path }} pkg install openssl"
  when:
    - ansible_facts['distribution'] in ["CentOS", "RedHat"] and ansible_facts['distribution_major_version'] >= "9" or
      ansible_facts['distribution'] == "Fedora" and ansible_facts['distribution_major_version'] >= "36"
  tags:
    - ruby

- name: Ensure correct ruby version is installed
  ansible.builtin.command: "{{ rvm_path }} install {{ ruby_version }} --with-openssl-dir={{ rvm_install_path }}/usr"
  tags:
    - ruby

- name: "Install rubygems cli"
  become: true
  ansible.builtin.package:
    name:
      - rubygems
    state: present
  tags:
    - ruby

- name: Ensure bundler is installed
  ansible.builtin.command: "gem install bundler"
  tags:
    - ruby

- name: Ensure correct ruby version is set as default
  ansible.builtin.command: "{{ item }}"
  loop:
    - "rvm --default use ruby-{{ ruby_version }}"
    - "rvm alias create default ruby-{{ ruby_version }}"
  tags:
    - ruby