---
- name: Ensure required openssl is installed
  ansible.builtin.command: "rvm pkg install openssl"
  when:
    - ansible_facts['distribution'] in ["CentOS", "RedHat"]
    - ansible_facts['distribution_major_version'] == "9"

- name: Ensure correct ruby version is installed
  ansible.builtin.command: "rvm install {{ ruby_version }} --with-openssl-dir=$HOME/.rvm/usr"

- name: Ensure bundler is installed
  ansible.builtin.command: "gem install bundler"

- name: Ensure correct ruby version is set as default
  ansible.builtin.command: "{{ item }}"
  loop:
    - "rvm --default use ruby-{{ ruby_version }}"
    - "rvm alias create default ruby-{{ ruby_version }}"
