# These tasks must be run as the candlepin user. main.yml imports this file with become_user set to
# {{ candlepin_user }}, but if these are included or imported anywhere else, that will likely need to
# be done there as well.
---
- name: "Checkout Candlepin Repo"
  ansible.builtin.git:
    repo: "{{ cp_git_repo }}"
    version: "{{ cp_git_ref }}"
    dest: "{{ candlepin_home }}"
    force: true
    clone: true
  when:
    - cp_git_checkout | bool
  tags:
    - candlepin
    - candlepin-setup

# Ensure Candlepin exists in a deployable state before attempting to run the bundle command
- name: "Ensure the Candlepin directory exists"
  ansible.builtin.stat:
    path: "{{ candlepin_home }}"
  register: candlepin_home_dir
  tags:
    - candlepin
    - candlepin-setup

# Impl note:
# This has to be done with a login shell to get the correct version of Ruby when using RVM
- name: "Install Candlepin gem bundle"
  ansible.builtin.shell: bash --login -c 'bundle install'
  args:
    chdir: "{{ candlepin_home }}"
  when:
    - cp_configure_ruby | bool
    - candlepin_home_dir.stat.exists and candlepin_home_dir.stat.isdir
  changed_when: false
  tags:
    - candlepin
    - candlepin-setup
