---
- name: "Install MariaDB packages"
  become: true
  package:
    name:
      - mariadb
      - mariadb-server
      - mariadb-java-client
      - python3-PyMySQL
    state: present
  tags:
    - candlepin
    - mariadb

- name: "Set Candlepin-specific MySQL configuration (collation-server)"
  become: true
  ini_file:
    path: /etc/my.cnf.d/candlepin.cnf
    mode: '0644'
    section: mysqld
    option: collation-server
    value: utf8_general_ci
    create: true
  tags:
    - candlepin
    - mariadb

- name: "Set Candlepin-specific MySQL configuration (character-set-server)"
  become: true
  ini_file:
    path: /etc/my.cnf.d/candlepin.cnf
    mode: '0644'
    section: mysqld
    option: character-set-server
    value: utf8
    create: true
  tags:
    - candlepin
    - mariadb

- name: "Set Candlepin-specific MySQL configuration (transaction-isolation)"
  become: true
  ini_file:
    path: /etc/my.cnf.d/candlepin.cnf
    mode: '0644'
    section: mysqld
    option: transaction-isolation
    value: READ-COMMITTED
    create: true
  tags:
    - candlepin
    - mariadb

- name: "Set Candlepin-specific MySQL configuration (default-time-zone)"
  become: true
  ini_file:
    path: /etc/my.cnf.d/mariadb-server.cnf
    section: server
    option: default-time-zone
    value: "+00:00"
    create: no
  tags:
    - candlepin
    - mariadb

- name: "Enable and start the MariaDB service"
  become: true
  service:
    name: mariadb.service
    enabled: true
    state: started
  tags:
    - candlepin
    - mariadb

# Impl note:
# Newer versions of MariaDB/MySQL restrict the root user a bit more than previous, causing our old user
# creation task to fail. We can work around this by reverting to the older authentication for the root
# user, but that's more insecure than just isolating the jank to the single user creation task and
# leaving the root account on the target system alone entirely.
#
# If this decision is ever flipped, the following tasks can be used to create the user with the mysql_user
# task instead:
#
# - name: "Allow insecure authentication for root"
#   become: true
#   command: "mysql -u root -e \"ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password;\""
#   tags:
#     - candlepin
#     - mariadb
#
# - name: "Create the 'candlepin' MariaDB user"
#   become: true
#   mysql_user:
#     name: candlepin
#     priv: "candlepin.*:ALL,GRANT"
#     state: present
#   tags:
#     - candlepin
#     - mariadb

- name: "Create the 'candlepin' MariaDB user"
  become: true
  command: "mysql --user root --execute=\"CREATE USER 'candlepin'@'localhost'; GRANT ALL PRIVILEGES on candlepin.* TO 'candlepin'@'localhost' WITH GRANT OPTION;\""
  tags:
    - candlepin
    - mariadb

- name: "Create the 'candlepin' MariaDB database"
  mysql_db:
    login_user: candlepin
    name: candlepin
    state: present
  tags:
    - candlepin
    - mariadb
