---
- name: "Include base deps tasks"
  ansible.builtin.import_tasks: el7_base_deps.yml

- name: "Include ruby tasks"
  ansible.builtin.import_tasks: el7_ruby.yml
  when:
    - cp_configure_ruby | bool
