---
- name: "Disable SELinux"
  become: true
  selinux:
    state: disabled
  tags:
    - system
    - candlepin

- name: "Update system packages"
  become: true
  package:
    name: "*"
    state: latest
  tags:
    - system
    - system_update
    - candlepin

- name: "Install Candlepin requirements"
  become: true
  package:
    name:
      - git
      - gcc
      - make
      - java-1.8.0-openjdk-devel
      - java-11-openjdk-devel
      - gettext
      - openssl
      - jss
      - tomcat
      - libxml2-python
      - python-requests
      - unzip
      - wget
      - zlib
      - zlib-devel
      - createrepo_c
      - rpm-build
      - rpm-sign
    state: present
  tags:
    - base_deps
    - candlepin

# Impl note:
# The invocations of alternatives need to be run in the context of the original user, but with
# root permissions. Using become and the raw shell command invokes these in root's environment,
# which will fail at best, or silently map the wrong command at worst.
- name: "Configure alternatives: java"
  shell: sh -c 'sudo alternatives --set java /usr/lib/jvm/java-11-openjdk-*/bin/java'
  tags:
    - base_deps
    - candlepin

- name: "Configure alternatives: javac"
  shell: sh -c 'sudo alternatives --set javac /usr/lib/jvm/java-11-openjdk-*/bin/javac'
  tags:
    - base_deps
    - candlepin

- name: "Update Tomcat configuration to use Alternatives-configured Java"
  become: true
  lineinfile:
    dest: /etc/tomcat/tomcat.conf
    regexp: "JAVA_HOME="
    line: "JAVA_HOME=\"/usr/lib/jvm/java\""
  tags:
    - base_deps
    - candlepin

- name: "Enable necessary ports in firewalld"
  become: true
  firewalld:
    port: "{{item}}/tcp"
    state: enabled
    permanent: true
    offline: false
  with_items:
    - 22
    - 443
    - 8080    # Candlepin Tomcat server
    - 8443    # ^
  when:
    - "'firewalld.service' in ansible_facts.services"
  tags:
    - system
    - candlepin
